name: Daily Update on Self-Hosted

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *' # 每日UTC+8 16时

env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
  GET_HOSTS_API: ${{ secrets.GET_HOSTS_API }}
  GET_HOSTS_API_PAYLOAD: ${{ secrets.GET_HOSTS_API_PAYLOAD }}
  GET_README_CONFIG: ${{ secrets.GET_README_CONFIG }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run : |
          pip3 install requests

      - name: Run main.py
        run : |
          python main.py > output.txt
          echo "updated=$(cat output.txt)" >> $GITHUB_ENV

      - name: Create SSH key
        if: ${{ env.updated == 'true' }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa

      - name: Upload updated file
        if: ${{ env.updated == 'true' }}
        run: |
          git config --global user.name "${{ secrets.USER_NAME }}"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          git config --global user.signingkey ~/.ssh/id_rsa
          git config --global gpg.format ssh
          git config --global commit.gpgsign true
          git add .
          git commit -S -m "$(date +"%Y年%m月%d日")更新"
          git push git@github.com:${{ github.repository }}.git HEAD:main

      - name: Close ssh-agent
        if: ${{ env.updated == 'true' }}
        run: |
          ps -eo pid,user,comm | grep ssh-agent | grep -w runner | awk '{print $1}' | xargs -r kill -9
          rm -rf $SSH_AUTH_SOCK

      # - uses: josStorer/get-current-time@v2.0.2
      #   if: ${{ env.updated == 'true' }}
      #   id: current-time
      #   with:
      #     format: YYYY-MM-DD HH:mm:ss
      #     utcOffset: "+08:00"

      # - uses: easychen/github-action-server-chan@v1.0.0
      #   if: ${{ env.updated == 'true' }}
      #   with:
      #     sendkey: ${{ secrets.sendkey }}
      #     title: "社区域名有更新"
      #     desp: "仓库更新于 ${{ steps.current-time.outputs.formattedTime }}"
